import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bibtime, BibtimeWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :bibtime, BibtimeWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      paths: ["/healthz"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Production runs a warm single-session pool instead of the `on_demand` mode
# used in dev and test.
#
# `on_demand` leaks Chrome: its teardown is a bare `Process.exit(browser,
# :normal)` that the browser survives, so every render adds ~3 OS processes
# that are never reclaimed — measured locally at roughly 400MB per export,
# which exhausts a small machine within a couple of exports. A pooled session
# keeps the process count flat and renders about three times faster. The cost
# is one Chrome resident from boot; `size: 1` keeps that to a single instance
# rather than the schedulers-online default.
#
# no_sandbox and --disable-dev-shm-usage are both needed for Chrome to run as
# an unprivileged user in a container: its own sandbox cannot initialise there,
# and the container's /dev/shm is far smaller than Chrome expects.
config :bibtime, ChromicPDF,
  on_demand: false,
  session_pool: [size: 1],
  no_sandbox: true,
  chrome_args: "--disable-dev-shm-usage"

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Richer metadata in stdout so the Fly → Better Stack log shipper has
# enough context to index. Better Stack auto-extracts the key=value pairs
# emitted by Logger.Formatter. See DEPLOY.md for the log shipper setup.
config :logger, :default_formatter,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id, :mfa, :file, :line, :crash_reason, :station_id, :race_id, :user_id]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
